sg/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from base.views import *

from medidores.views import *
from unidades.views import *

from medidores.views import *
from unidades.views import *

from django.views.generic.base import TemplateView
from django.conf.urls import handler404
from base.views import handler404,handler500
from django.conf import settings
from django.conf.urls.static import static
handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'


urlpatterns = [
	url(r'^$', index ,name='home'),
    url(r'^usuarios/$', lista_usuarios ,name='list_user'),
    url(r'^admin/', admin.site.urls),   
    url(r'^login/$', auth_views.login, {'template_name': 'base/login.html'}, name='login'),
    url(r'^user/new/$', add_user, name='add_user'),
    url(r'^user/edit/(?P<pk>\d+)/$', edit_user, name='edit_user'),
    url(r'^user/delete/(?P<pk>\d+)/$', delete_user, name='delete_user'),
    url(r'^logout/$', auth_views.logout, name='logout'),

    #medidores
    url(r'^medidores/$', lista_medidores ,name='lista_medidores'),
    url(r'^medidores/agregar/$', add_medidores ,name='add_medidor'),
    url(r'^medidores/editar/(?P<pk>\d+)/$', edit_medidores ,name='edit_medidor'),
    url(r'^medidores/eliminar/(?P<pk>\d+)/$', delete_medidor ,name='delete_medidor'),

    #unidades
    url(r'^unidades/$', lista_unidades ,name='lista_unidades'),
    url(r'^agregar_unidad/$', add_unidad ,name='add_unidad'),

    #direcciones
    url(r'^direcciones/$', lista_direcciones ,name='lista_direccion'),
   # url(r'^agregar_direcciones/$', add_direcciones ,name='add_direcciones'),

    #Radios
    url(r'^radios/$', lista_radios ,name='lista_radio'),
    url(r'^agregar_radios/$', add_radios ,name='add_radio'),
    url(r'^radio_detalle/(?P<pk>\d+)/$', radio_detalle ,name='radio_detalle'),
    url(r'^unidad_consumo/$', add_unidadConsumo ,name='add_unidadConsumo'),
    url(r'^detalle_unidad/(?P<pk>\d+)/$', detalle_unidad ,name='detalle_unidad'),
    url(r'^radio/edit/(?P<pk>\d+)/$', edit_radio, name='edit_radio'),
    url(r'^radio/delete/(?P<pk>\d+)/$', delete_radio, name='delete_radio'),
    
    #orden de servicio
    url(r'^agregar_orden/$', orden_servicio ,name='orden_servicio'),
    url(r'^lista_ordenes/$', lista_os , name='lista_orden'),
    #apis
   url(r'^api/', include('apis.urls', namespace='api')),

    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medidores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from unidades.models import Radio,UnidadConsumos, Direccion
# Create your models here.


class Medidor(models.Model):
	tag = models.CharField(max_length=250)
	modelo = models.CharField(max_length=250,null=True,default='demo')
	version_fw= models.CharField(max_length=250,default=True)
	num_medidor = models.CharField(max_length=20,unique=True)
	clave_pac= models.CharField(max_length=250,default=True)
	punto= models.CharField(max_length=250,default=True)
	radio=models.ForeignKey(Radio,default=True)
	unidad_consumo = models.ForeignKey(UnidadConsumos,null=True)

class OrdenServicio(models.Model):
	LECTURA = (
		('AB','Abierto'),
		('CR','Cerrado')
		)
	STATUS = (
		('EP','EnProceso'),
		('PU','Pausada'),
		('AB','Abortada'),
		('CM','Completada'),
		('DS','Desconocido')
		)

	consumo = models.CharField(max_length=250)
	status_ultima_lectura= models.CharField(choices=LECTURA,max_length=3)
	fecha_ultima_lectura = models.DateTimeField(auto_now_add=True)
	is_active = models.BooleanField(default=True)
	status_os = models.CharField(default='EnProceso', null=True,max_length=9)
	descripcion = models.CharField(max_length=250)
	medidor = models.ForeignKey(Medidor,null=True)


class Grafica(models.Model):
	registro=models.CharField(max_length=250)
	dias = models.CharField(max_length=50)

unidades/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Municipio(models.Model):
	ESTADOS = (
		('AGS', 'Aguascalientes'),
		('BC', 'Baja California'),
		('BCS', 'Baja California Sur'),
		('CAM', 'Campeche'),
		('CHP', 'Chiapas'),
		('CHI', 'Chihuahua'),
		('DIF', 'Ciudad de México'),
		('COA', 'Coahuila'),
		('COL', 'Colima'),
		('DUR', 'Durango'),
		('GTO', 'Guanajuato'),
		('GRO', 'Guerrero'),
		('HGO', 'Hidalgo'),
		('JAL', 'Jalisco'),
		('MEX', 'México'),
		('MIC', 'Michoacán'),
		('MOR', 'Morelos'),
		('NAY', 'Nayarit'),
		('NLE', 'Nuevo León'),
		('OAX', 'Oaxaca'),
		('PUE', 'Puebla'),
		('QRO', 'Querétaro'),
		('ROO', 'Quintana Roo'),
		('SLP', 'San Luis Potosí'),
		('SIN', 'Sinaloa'),
		('SON', 'Sonora'),
		('TAB', 'Tabasco'),
		('TAM', 'Tamaulipas'),
		('TLX', 'Tlaxcala'),
		('VER', 'Veracruz'),
		('YUC', 'Yucatán'),
		('ZAC', 'Zacatecas')
	)
	nombre = models.CharField(max_length=255)
	estado = models.CharField(choices=ESTADOS, max_length=3)

class Direccion(models.Model):
	calle = models.CharField(max_length=255)
	numero = models.IntegerField()
	colonia = models.CharField(max_length=255)
	codigo_postal= models.CharField(max_length=10)
	municipio = models.ForeignKey(Municipio)
	longitud = models.CharField(max_length=240)
	latitud = models.CharField(max_length=240)

class Radio (models.Model):
	clave = models.CharField(max_length=6,unique=True)
	tag_radio = models.CharField(max_length=255)
	modelo = models.CharField(max_length=250,null=True,default=True)
	version_fw = models.CharField(max_length=250,null=True,default=True)
	protocolo = models.CharField(max_length=250,null=True,default=True)
	direccion = models.ForeignKey(Direccion)


class UnidadConsumos(models.Model):
	unidad_consumo = models.CharField(max_length=60)
	tag_unidad_consumo = models.CharField(max_length=255)
	radio = models.ForeignKey(Radio, null=True)


class Unidad(models.Model):
	ubicacion = models.ForeignKey(Direccion,null=True)
	status_unidad = models.BooleanField(default=True)
	status_comunicacion_unidad=models.BooleanField(default=True)
	status_conecxion = models.BooleanField(default=True)

medidores/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponseNotFound
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from unidades.models import *
from medidores.models import *
# Create your views here.



#Medidores
def lista_medidores(request):
	if	request.user.is_superuser:
		medidores = Medidor.objects.all()
		return  render(request,'medidores/lista_medidores.html',{'medidores':medidores})
	else:
		return HttpResponseNotFound('<h1>Page not found</h1>')

def add_medidores(request):
	if request.method == 'POST':
		num_medidor =request.POST.get('num_medidor')
		tag_medidor = request.POST.get('tag_medidor')
		modelo= request.POST.get('modelo')
		version_fw=request.POST.get('version_fw')
		clave_pac = request.POST.get('clave_pac')
		punto=request.POST.get('punto')
		radio_id = request.POST.get('radio')
		if request.POST.get('medidor_id'):
			medidor = Medidor.objects.get(id=request.POST.get('medidor_id'))
			medidor.num_medidor = num_medidor
			medidor.tag=tag_medidor
			medidor.radio_id=radio_id
			medidor.modelo=modelo
			medidor.version_fw=version_fw
			medidor.clave_pac=clave_pac
			medidor.save()
			return redirect('/medidores/')
		else:
			medidores= Medidor(num_medidor=num_medidor, tag=tag_medidor, radio_id=radio_id,modelo=modelo,version_fw=version_fw,clave_pac=clave_pac)
			medidores.save()
			return redirect('/medidores/')
	else:
		radios = Radio.objects.all()
		return render(request,'medidores/add_medidores.html',{'radios':radios}	)

def edit_medidores(request,pk):
	medidor = Medidor.objects.get(id=pk)
	radios = Radio.objects.all()
	env = {
		'medidor':medidor,
		'radios':radios
	}

	return render(request,'medidores/add_medidores.html',env)

	
def delete_medidor(request,pk):
	Medidor.objects.get(id=pk).delete()
	return redirect('/medidores/')
#Ordenes de Servicio
def orden_servicio(request):
	if request.method == 'POST':
		consumo = request.POST.get('consumo')
		status_ultima_lectura=request.POST.get('status')
		fecha_ultima_lectura=request.POST.get('fecha')
		is_active=request.POST.get('os')
		descripcion =request.POST.get('descripcion')

		orden = OrdenServicio(consumo=consumo,status_ultima_lectura=status_ultima_lectura,fecha_ultima_lectura=fecha_ultima_lectura,is_active=is_active,descripcion=descripcion)
		orden.save()
		return redirect('/lista_ordenes/')
	else:
		medidores = Medidor.objects.all()
		orden = OrdenServicio.LECTURA
		
		env={
		'orden':orden,
		'medidores':medidores,
		}
		return render(request,'unidades/orden_servicio/add_orden_servicio.html',env)


def lista_os(request):

	orden_servicio= OrdenServicio.objects.all()
	user = User.objects.all().filter(is_active=True)
	env = {

	'orden_servicio':orden_servicio,
	'user':user,

	}
	return render (request,'unidades/orden_servicio/list_orden_servicio.html',env)

templates/medidores/add_medidores.html
{%extends 'base/base.html'%}


{%block content%}

      <div class="content">
          {% if num %}
          <div class="container">
            <div class="col-sm-12 ">
            <div class="alert alert-danger">
            <span>El medidor <b> {{num}} </b> ya existe.</span>
            </div>
            </div>
          </div>
          {% endif %}
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">

            <div class="col-md-12">
              <div class="card ">
                <div class="card-header card-header-rose card-header-text">
                  <div class="card-text">
                    <h4 class="card-title">Agregar Medidor</h4>
                  </div>
                </div>
                <div class="card-body ">
                  <form method="post" action="{%url 'add_medidor'%}" class="form-horizontal">{% csrf_token %}
                    <div class="row">
                      <input type="hidden" value="{{medidor.id}}" name="medidor_id" id="medidor_id">
                      <label class="col-sm-2 col-form-label">Numero de Medidor</label>
                      <div class="col-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="num_medidor" name="num_medidor"  value="{{medidor.num_medidor}}" autocomplete="off" required maxlength="20"  pattern="[0-9]{20}" title="Solo numeros. Tamaño máximo: 20">
                          <p style="display:none;"  class="text-danger" id="existe">El Numero de medidor ya existe</p>
                 
                        </div>
                      </div>
                      <label class="col-sm-2 col-form-label">Modelo de Medidor</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="modelo" name="modelo" value="{{medidor.modelo}}" required >
                        </div>
                      </div>
                      <label class="col-sm-2 col-form-label">Punto de Medidor</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="punto" name="punto" value="{{medidor.punto}}" required >
                        </div>
                      </div>
                      <label class="col-sm-2 col-form-label">Tag de Medidor</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="tag_medidor" name="tag_medidor" value="{{medidor.tag}}" required >
                        </div>
                      </div>
                    <label class="col-sm-2 col-form-label">Version FW de Medidor</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="version_fw" name="version_fw" value="{{medidor.version_fw}}" required >
                        </div>
                      </div>
                      <label class="col-sm-2 col-form-label">ID de PAC</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="clave_pac" name="clave_pac" value="{{medidor.clave_pac}}" required >
                        </div>
                      </div>
                    </div>
                    </div>
                    </div>
                      <div class="card ">
                      <div class="card-header card-header-rose card-header-text">
                  <div class="card-text">
                    <h4 class="card-title">Asignar Radio</h4>
                  </div>
                </div>
                <div class="card-body ">
                       <div class="row">
                      <label class="col-sm-2 col-form-label">Id de Radios</label>
                      <div class="col-4">
                        <div class="form-group">
                              <select name="radio" id="radios" class="form-control" required >
                                <option value="0" selected="true" disabled="disabled">
                                Selecciona un radio
                              </option>
                                {% for radio in radios  %}
                                  <option data-modelo="{{radio.modelo}}"
                                  data-version="{{radio.version_fw}}"
                                  data-protocolo="{{radio.protocolo}}" 
                                  data-latitud="{{radio.direccion.latitud}}"
                                  data-calle="{{radio.direccion.calle}}"
                                  data-numero="{{radio.direccion.numero}}"
                                  data-colonia="{{radio.direccion.colonia}}"
                                  data-codigopostal="{{radio.direccion.codigo_postal}}"
                                  data-estado="{{radio.direccion.municipio.estado}}"
                                  data-municipio="{{radio.direccion.municipio.nombre}}"
                                  data-longitud="{{radio.direccion.longitud}}"
                                  value="{{radio.id}}" 
                                  {% if radio.id == medidor.radio.id %}
                                    selected="selected"
                                  {% endif %}
                                  >
                                  {{radio.clave}}
                                </option>
                                {% endfor %}
                              </select>
                        </div>
                      </div>                     
                      <label class="col-sm-2 col-form-label">Modelo de Radio</label>
                      <div class="col-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="r_modelo" name="r_modelo" value="{{medidor.radio.modelo}}" readonly required>
                        </div>
                      </div>  
                      <label class="col-sm-2 col-form-label">Version FW de Radio</label>
                      <div class="col-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="r_version" name="r_version" value="{{medidor.radio.version_fw}}" readonly required>
                        </div>
                      </div>               
                      <label class="col-sm-2 col-form-label">Protocolo de radio</label>
                      <div class="col-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="r_protocolo" name="r_protocolo" value="{{medidor.radio.protocolo}}" readonly required>
                        </div>
                      </div>
                    
                   </div>
                   <div class="row">
                    <div class="card-body text-center">
                      <h4 class="card-title pl-3">Dirección
                
              </h4>
                      <div class="row">
                      <label class="col-sm-2 col-form-label">Calle</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="calle" name=""  value="{{medidor.radio.direccion.calle}}" disabled="disabled" >
                           </div>
                      </div>
                  
                      <label class="col-sm-2 col-form-label">Numero</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="numero" name="" value="{{medidor.radio.direccion.numero}}" disabled="disabled">
                        </div>
                      </div>
                    
                      <label class="col-sm-2 col-form-label">Colonia</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="colonia" name="" value="{{medidor.radio.direccion.colonia}}" disabled="disabled">
                        </div>
                      </div>
                    
                      <label class="col-sm-2 col-form-label">Codigo Postal</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="codigopostal" name="" value="{{medidor.radio.direccion.codigo_postal}}" disabled="disabled">
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <label class="col-sm-2 col-form-label">Estado</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="estado" name="" value="{{medidor.radio.direccion.municipio.get_estado_display}}" disabled="disabled">
                        </div>
                      </div>
           
                      <label class="col-sm-2 col-form-label">Municipio</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                        <input type="text" class="form-control" id="municipio" name="" value="{{medidor.radio.direccion.municipio.nombre}}"  disabled="disabled">
                        </div>
                      </div>
                    </div>
                     <div class="row">
                      <label class="col-sm-2 col-form-label">Longitud</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="longitud" name="" value="{{medidor.radio.direccion.longitud}}" disabled="disabled">
                        </div>
                      </div>
                 
                      <label class="col-sm-2 col-form-label">Latitud</label>
                      <div class="col-sm-4">
                        <div class="form-group">
                          <input type="text" class="form-control" id="latitud" name="" value="{{medidor.radio.direccion.latitud}}" readonly disabled="disabled">
                        </div>
                      </div>
                    </div>
                   </div>

                    </div>
                    <div class="col-md-3 ml-auto">
                    <input id="tipob" type="submit" value="Guardar" class="btn btn-success"></div>
                  </form>
                </div>
              </div>
            </div>



 {%endblock%}
 {%block scripts%}
  <script>
    $(function() {
      $("#num_medidor").focusout(function(event) {
             validar_medidor($(this).val());
        });

      $('#radios').change(function(event) {

          var modelo= $(this).find(':selected').data('modelo');
          var version= $(this).find(':selected').data('version');
          var protocolo= $(this).find(':selected').data('protocolo');
          var latitud= $(this).find(':selected').data('latitud');
          var calle= $(this).find(':selected').data('calle');
          var numero= $(this).find(':selected').data('numero');
          var colonia= $(this).find(':selected').data('colonia');
          var codigopostal= $(this).find(':selected').data('codigopostal');
          var estado= $(this).find(':selected').data('estado');
          var municipio= $(this).find(':selected').data('municipio');
          var longitud= $(this).find(':selected').data('longitud');

          
          $('#r_modelo').val(modelo);
          $('#r_version').val(version);
          $('#r_protocolo').val(protocolo);
          $('#latitud').val(latitud);
          $('#calle').val(calle);
          $('#numero').val(numero);
          $('#colonia').val(colonia);
          $('#codigopostal').val(codigopostal);
          $('#estado').val(estado);
          $('#municipio').val(municipio);
          $('#longitud').val(longitud);




      });
    });
    function validar_medidor(num_medidor){
      $.ajax({
        url: '/api/medidor/'+num_medidor,
      })
      .done(function() {
        console.log("success");

        $('#existe').css("display", "block");
          
      })
      .fail(function() {
        console.log("error");
        $('#existe').css("display", "none");
      });
      
    }

  </script>
 {%endblock scripts%}

templates/medidores/lista_medidores.html
{%extends 'base/base.html'%}
{%block head%}
      <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
      <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.bootstrap.min.css">
      <link rel="stylesheet" href="https://cdn.datatables.net/select/1.2.5/css/select.bootstrap.min.css ">
{%endblock%}


  {%block encabezado%}Medidores{%endblock%}
  {%block content%}


  <div class="content">
  <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                  <div class="card-icon">
                    <i class="material-icons">assignment</i>
                  </div>
                  <h4 class="card-title">Listado de Medidores</h4>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="text-center">#</th>
                          <th>Numero de Medidor</th>
                          <th>Modelo de Medidor</th>
                          <th>Tag del Medidor</th>
                          <th>Id del Radio</th>
                          <th>Direccion</th>
                          <th class="">Acciones</th>
                        </tr>
                      </thead>
                      <tbody>
                        {%for medidor in medidores%}
                        <tr>
                          <td class="text-center">{{medidor.id}}</td>
                          <td>{{medidor.num_medidor}}</td>
                          <td>{{medidor.modelo}}</td>
                          <td>{{medidor.tag}}</td>
                          <td>{{medidor.radio.clave}}</td>
                          <td>{{medidor.radio.direccion.calle}}</td>

                          <td class="td-actions">
                            
                            <a href="{%url 'edit_medidor' pk=medidor.id%}" class="btn btn-success btn-link">
                              <i class="material-icons">edit</i>
                            </a>
                            
                            <a href="{%url 'delete_medidor' pk=medidor.id%}" class="btn btn-danger btn-link" >
                              <i class="material-icons">close</i>
                            </a>
                          </td>
                        </tr>
                        {%endfor%}

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>



  {%endblock%}